# Generated by Django 2.2.3 on 2019-09-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('Engine', models.CharField(max_length=100)),
                ('odometer', models.IntegerField()),
                ('state_reg', models.TextField(max_length=2)),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('wishlist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='maintenance date')),
                ('odo_Reading', models.IntegerField()),
                ('task', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
