# Generated by Django 2.2.5 on 2019-09-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='odo_Reading',
            new_name='odo_reading',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
