# Generated by Django 2.2.3 on 2019-09-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='to_do',
        ),
    ]
